# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-17 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
    ]
